{
 "title": "hello dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "system cpu" },
    { "expr": "process_cpu_usage", "legendFormat": "process cpu" }
   ]
  },
  {
   "title": "Disk 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "disk_total_bytes", "legendFormat": "전체 용량" },
    {
     "expr": "disk_total_bytes - disk_free_bytes",
     "legendFormat": "사용 용량"
    }
   ]
  },
  {
   "title": "주문수 Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(metric_order_total{method=\"order\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "increase(metric_order_total{method=\"cancel\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "주문수 Timer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "increase(metric_order_seconds_count{method=\"order\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "increase(metric_order_seconds_count{method=\"cancel\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "주문 평균 실행시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(metric_order_seconds_sum{method=\"order\"}[1m]) / increase(metric_order_seconds_count{method=\"order\"}[1m])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "increase(metric_order_seconds_sum{method=\"cancel\"}[1m]) / increase(metric_order_seconds_count{method=\"cancel\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "주문 최대 실행 시간",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "metric_order_seconds_max{method=\"order\"}",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "metric_order_seconds_max{method=\"cancel\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "재고",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "metric_stock", "legendFormat": "stock" }
   ]
  }
 ]
}